// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","id":"1"},"2":{"path":"/","id":"2"},"3":{"path":"/","redirect":"/datasources","parentId":"2","id":"3"},"4":{"path":"/datasources","parentId":"2","id":"4"},"5":{"path":"/workbench","parentId":"2","id":"5"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__layouts__MainLayout" */'@/pages/layouts/MainLayout.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__datasources__index" */'@/pages/datasources/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__workbench__index" */'@/pages/workbench/index.tsx')),
},
  };
}
